config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get 'sessions/new'

  root 'pages#home'
  post 'pages/home'
  post 'pages/save'
  post 'pages/loader'
  post 'pages/getusers'
  post 'pages/changepriv'
  
  post 'users/register'
  post 'users/test'
  post 'users/new'
  
  get 'sessions/new'
  post 'sessions/login'
  post 'sessions/create'
  
  delete 'sessions/destroy'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  #def show
  #end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  #def edit
  #end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end
=begin
  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:id, :lat, :long)
    end
=end    
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Lat</th>
      <th>Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.id %></td>
        <td><%= location.lat %></td>
        <td><%= location.long %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @location.id %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @location.long %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>